name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.neon-gist-439401-k8 }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.neon-gist-439401-k8 }}/my-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-app \
          --image gcr.io/${{ secrets.neon-gist-439401-k8 }}/my-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated



******************************************************
name: Deploy to Compute Engine VM

on:
  push:
    branches:
      
main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v2

      
name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

      
name: Configure VM instance
      run: |
        gcloud compute instances create my-app-vm \--zone=us-central1-a \--machine-type=n2-standard-2 \--image-family=debian-11 \--image-project=debian-cloud \--boot-disk-size=20GB \--scopes=https://www.googleapis.com/auth/cloud-platform \--tags=http-server,https-server

      
name: SSH into VM and deploy app
      run: |# Copy the application code to the VM
        gcloud compute scp --recurse ./ my-app-vm:/home/app \--zone=us-central1-a

          # SSH into the VM and run the deployment commands
          gcloud compute ssh my-app-vm --zone=us-central1-a --command="
            sudo apt update && sudo apt install -y docker.io;
            sudo docker build -t my-app /home/app;
            sudo docker run -d -p 80:80 my-app;
          "

